# -*- coding: utf-8 -*-
"""carla-rosa-tipos-de-testes-gabarito.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FFgLZ69ZJN5fWCWfLqXJjqZygDGqNvUw

> # <b>PROGRAMA GERENCIADOR DE NÚMEROS</b>   
Exemplo de uma programa em <i>JavaScript</i> para realizar diferentes tipos de testes.  
Inclua uma nova célula de código clicando em <b>`+ Código`</b>, copie  o código do teste  
e execute a célula com o botão ▶️, conforme as instruções no <i>Google Classroom</i>.
"""

# Lista global que armazenará os números adicionados
numbers = []

# Função para adicionar um número à lista
def add_number(n):
    numbers.append(n)  # Adiciona o número à lista
    print(f"Número {n} adicionado. Lista atual: {numbers}")  # Exibe o número adicionado e o estado atual da lista

# Função para remover um número da lista, se ele existir
def remove_number(n):
    if n in numbers:  # Verifica se o número está na lista
        numbers.remove(n)  # Remove o número
        print(f"Número {n} removido. Lista atual: {numbers}")  # Exibe confirmação e estado da lista
    else:
        print(f"Número {n} não encontrado na lista.")  # Informa que o número não está presente

# Função para calcular a média dos números na lista
def average():
    if not numbers:  # Verifica se a lista está vazia
        print("Lista vazia. Média = 0")  # Mensagem informativa
        return 0  # Retorna 0 como média padrão
    media = sum(numbers) / len(numbers)  # Calcula a média
    print(f"Média atual dos números {numbers} = {media}")  # Exibe a média e os números usados
    return media  # Retorna o valor da média

# 🔍 Exemplos de uso das funções

# Adiciona o número 10 à lista
add_number(10)     # Esperado: Lista atual: [10]

# Adiciona o número 20 à lista
add_number(20)     # Esperado: Lista atual: [10, 20]

# Adiciona o número 30 à lista
add_number(30)     # Esperado: Lista atual: [10, 20, 30]

# Adiciona o número 30 à lista
add_number(40)     # Esperado: Lista atual: [10, 20, 30, 40]

# Calcula a média dos números atuais
average()          # Esperado: Média = (10 + 20 + 30 + 40) / 4 = 25.0

# Remove o número 10 da lista
remove_number(10)  # Esperado: Lista atual: [20, 30, 40]

# Calcula a nova média após a remoção
average()          # Esperado: Média = (20 + 30 + 40) / 3 = 30.0

# Tenta remover o número 50, que não está na lista
remove_number(50)  # Esperado: Mensagem de número não encontrado

# 🔄 Teste Relacionado à Mudança
remove_number(20)     # Remove o número 20 da lista, se estiver presente
print(average())      # Calcula e exibe a nova média após a remoção

# 🚀 Teste Não-Funcional – Desempenho
import time  # Importa o módulo para medir duração da execução e avaliar desempenho do código

numbers = list(range(1_000)) # Preenche a lista com 1000 números
start = time.time() # Marca o tempo inicial
average() # Executa a função que queremos medir
end = time.time() # Marca o tempo final
execution_time = end - start # Calcula o tempo decorrido
print(f"Tempo de execução: {execution_time:.6f} segundos")

# 🔐 Teste Não-Funcional – Segurança (simulado)
add_number("dez")     # Tenta adicionar uma string em vez de um número (entrada inválida)
print(numbers)        # Exibe o conteúdo da lista após a inserção
print(average())      # Tenta calcular a média com um valor não numérico na lista

# 🧪 Teste não-funcional – usabilidade
numbers = []      # Lista vazia, simula ausência de entrada do usuário
print(average())     # Tenta calcular a média e exibe a resposta do sistema

# 📈 Teste de Carga
for i in range(1_000): # Repete 1000 vezes, de 0 até 999
    add_number(i) # Adiciona número à lista usando a função range()

# Exibe quantos números foram adicionados
print(f"Adicionados", len(numbers), "números.")
# Esperado: Adicionados 1000 números.

# 💥 Teste de stress
numbers = []  # Garante que a lista esteja vazia
for _ in range(1_000):
    add_number(1)       # Adiciona o número 1 à lista
    remove_number(1)    # Remove o número 1 da lista

print(numbers)          # Exibe o estado final da lista

# 🧪 Teste de compatibilidade
import sys  # Importa módulo para acessar informações do sistema, como a versão do Python

print("Versão do Python:", sys.version)  # Exibe a versão atual do interpretador
average()   # Executa a função average(), que imprime o resultado

# 🧠 Teste Exploratório
add_number(None)     # Adiciona um valor nulo (None), que não é um número
add_number(True)     # Adiciona um valor booleano (True), que é interpretado como 1 em operações numéricas
add_number(3.14)     # Adiciona um número de ponto flutuante ou decimal(válido)

print(numbers)       # Exibe o conteúdo atual da lista, inclui valores adicionados
print(average())     # Tenta calcular a média com os valores atuais, o que pode gerar erro de tipos forem incompatíveis

# 🧪 Teste A/B

def average_a():
    # Versão A: calcula a média sem arredondar
    return sum(numbers) / len(numbers)

def average_b():
    # Versão B: calcula a média e arredonda para 2 casas decimais
    return round(sum(numbers) / len(numbers), 2)

# Lista de entrada com números inteiros e um número decimal
numbers = [10, 20, 30, 35.5]

# Exibe o resultado da versão A (sem arredondamento)
print("A:", average_a())

# Exibe o resultado da versão B (com arredondamento)
print("B:", average_b())